sudo: false
language: python
branches:
    only:
      - master
python:
  - "2.7.11"
install:
  - pip install -r test-requirements.txt
script:
  - pip install --upgrade cffi
  - pip freeze
  - pep8 .
  - pylint build_pipeline
  - coverage run --source=build_pipeline -m nose
after_success:
  - pip install coveralls==1.0
  - coveralls
